var PLACE_DATA = {
    town:{
        name:'Arcadia',
        resource:{
            tree:{
                name:'Farm',
                things:{wheat:3},
                circle:0.2,
                timeNeed:1,
                action:'Collect',
                require:{ps:3},
                initAmount:15
            },
            part:{
                name:'Components',
                things:{part:2},
                circle:0.5,
                timeNeed:1,
                action:'Collect',
                require:{ps:2},
                initAmount:10,
            },

            gold:{
                name:'Gold',
                things:{gold:10},
                circle:1,
                timeNeed:0.1,
                action:'Steal',
                require:{ps:3},
                initAmount:100,
                event:'denBox'
            },
            gem:{
                name:'Gem',
                things:{gem:10},
                circle:1,
                timeNeed:0.1,
                action:'Steal',
                require:{ps:3},
                initAmount:50,
                event:'denBox'
            },
        },
        things:{
            wood:20,
            seed:40,
            part:20,
        },
        mst:{},
        event:{
            trade:true,
            miner:true,
            farmer_1:true,
            farmer_2:true,
            farmer_3:true,
            farmer_end:true,
            robberQuestGet:true,
            robberQuest:true,
            spiderQuestGet:true,
            spiderQuest:true,
            dragonQuestGet:true,
            dragonQuest:true,
            misteryQuest_1:true,
            misteryQuest_2:true,
            misteryQuest_3:true,
            gulf:true,
        },
        requireEvent:'tramp',
        timeNeed:0.5
    },
    upgradePlace:{
        name:'Academy',
        timeNeed:1,
        science:'upgradePlace',
    },
    forest:{
        event:{
            tramp:true
        },
        name:'Silent Forest',
        resource:{
            tree:{
                name:'Tree',
                things:{bark:2,wood:5},
                circle:0.5,
                timeNeed:1,
                action:'Chop',
                require:{ps:5,axe:1},
                initAmount:30
            },
            fruitCluster:{
                name:'Berry',
                things:{fruit:3},
                circle:0.1,
                timeNeed:0.5,
                action:'Collect',
                require:{ps:3},
                initAmount:10
            },
            herbCluster:{
                name:'Herb',
                things:{herb:3},
                circle:0.1,
                timeNeed:0.5,
                action:'Collect',
                require:{ps:3},
                initAmount:10
            },

        },
        mst:{
            scaryFlower:{
                balancedAmount:15
            },
            butterFly:{
                balancedAmount:12
            },
        },
        things:{
            wood:20,
            fruit:20,
            flower:20,
            seed:30,
            bark:10,
        },
        timeNeed:1
    },
    river:{
        name:'The River',
        resource:{
            tree:{
                name:'Tree',
                things:{bark:2,wood:5},
                circle:0.3,
                timeNeed:1,
                action:'Chop',
                require:{ps:5,axe:1},
                initAmount:15
            },
            brook:{
                name:'River',
                things:{water:4},
                circle:0.3,
                timeNeed:1,
                action:'Collect',
                require:{ps:5},
                initAmount:40
            },
            flowerCluster:{
                name:'Poison Flower',
                things:{flower:3,seed:3,poizonRoot:1},
                circle:0.2,
                timeNeed:0.5,
                action:'Collect',
                require:{ps:3},
                initAmount:10
            }
        },
        things:{
            water:20,
            fruit:20,
            poizonRoot:10,
            flower:8,
            seed:8,
        },
        mst:{
            crow:{
                balancedAmount:15
            },
        },
        timeNeed:2,
        event:{
            map_1:true,
            map_2:true,
            map_3:true,
            map_4:true,
        }
    },
    }
